services:
  - type: web
    name: backend
    env: docker
    rootDir: backend
    buildCommand: docker build -t backend .
    startCommand: docker run -p $PORT:8000 backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
